import type { Metadata } from 'next';
import { Geist, Geist_Mono, Exo } from 'next/font/google';
import './globals.css';
import Navbar from './_Components/Navbar/Navbar';
import Footer from './_Components/Footer/Footer';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });
const exo = Exo({
  variable: '--font-exo',
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'FreshCart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${exo.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
