import type { Metadata } from 'next';
import { Geist, Geist_Mono, Exo } from 'next/font/google';
import './globals.css';
import Navbar from './_Components/Navbar/Navbar';
import Footer from './_Components/Footer/Footer';
import { Toaster } from '@/components/ui/sonner';
import MyProvider from './_Components/MyProvider/MyProvider';
const exo = Exo({
  variable: '--font-exo',
  subsets: ['latin'],
});
export const metadata: Metadata = {
  title: 'FreshCart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${exo.className} antialiased`}>
        <MyProvider>
          <Navbar />
          <Toaster
            position="top-right"
            richColors
            toastOptions={{
              duration: 4000,
              className: 'custom-toast',
            }}
          />
          {children}
          <Footer />
        </MyProvider>ِ
      </body>
    </html>
  );
}
